import { Geist, Geist_Mono, Archivo_Black } from "next/font/google";
import Header from "./Components/Header/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-archivo-black",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} ${archivoBlack.variable}`}>
        <div className="flex flex-col min-h-screen">
          {/* <Header /> */}
          <main className="flex-grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
